### ISSUE TITLE
ERROR LOGIN no GRANT ACCESS

### ISSUE THREAD

**Issue by danbjoseph** [openstreetcam/upload-scripts#53] opened 2018-05-23 18:12 UTC
problems uploading. i've gotten it to work on another computer. not sure what's up now.
```
(venv) ➜  upload_photos_by_exif git:(master) ✗ ./upload_exif.py -p /Users/danbjoseph/Desktop/mapillary/100MSDCF/0/success

For login go to this URL in your browser:
http://www.openstreetmap.org/oauth/authorize?oauth_token=Zq0xqjK2hQlNcDG3gxScUAItcKU3A25bTGORYu8N
Login and  grant acces then press ENTER

"Decoder failed to handle oauth_token with data as returned by provider. A different decoder may be needed. Provider returned: b''"
ERROR LOGIN no GRANT ACCESS
(venv) ➜  upload_photos_by_exif git:(master) ✗ python --version
Python 3.5.4
```

**Comment by n76** [comment] 2018-06-03 22:57
This might be a duplicate of https://github.com/openstreetcam/upload-scripts/issues/52

**Comment by bogdans-telenav** [comment] 2018-06-08 08:58
This should be fixed it was related to a change in the OSM OAuth service.

**Closed by bogdans-telenav** 2018-06-08 08:58 UTC
